Dev
java-park-mail-ru/LastUnion-09-2017 pull request #2
Opened 2017-10-18 22:32 UTC by HaseProgram

Ready for RK2

2017-10-19 07:46 UTC, isopov commented
РК2 так РК2 - я только примененного PR к РК1 не вижу ;-)

2017-10-19 08:25 UTC, isopov commented
1. Почистите лишние зависимости - spring-boot-configuration-processor ? spring-security-web ?
2. Несколько `@JsonCreator` на одном классе работает по счастливой случайности, а вообще не должно (ResponseCode)
3. Создание схемы сделайте через flyway
4. В базу из приложения не ходите из-под postgres
5. Чтобы не приходилось определять локально переменную окружения или править application.properties, можно определить урл к базе как-то так - `spring.datasource.url=${JDBC_DATABASE_URL:jdbc:postgresql://localhost/lastunion}`
6. Зачем junit-категории?
7. Константы лучше определять как константы - то есть public|private static final String
8. В тестах не бойтесь `throws Exception` - там хоть все методы такими могут быть, оборачивать в RuntimeException - только лишние строчки кода
9. А вообще `@SuppressWarnings("ThrowInsideCatchBlockWhichIgnoresCaughtException")` - зря игнорируете - это очень правильное замечание Идеи к вашему коду
10. lastunion.application.dao.UserDAO.modifyUser(UserModel, UserModel) - перепишите на параметризованный запрос - собирать самому из строчек - нельзя. (saveUser & deleteUserByName тоже)
11. Что вы думаете о таких методах? зачем они нужны?
```
    private void executeQuery(String query) {
        jdbcTemplate.update(query);
    }

    private String makePasswordHash(@NotNull final String password) {
        return passwordEncoder().encode(password);
    }

    private boolean checkPassword(@NotNull final String password, @NotNull final String passwordHash) {
        return passwordEncoder().matches(password, passwordHash);
    }

```
12. `@CrossOrigin` - скопирован между контроллерами, вынесите хоть в константу аргумент этих аннотаций
13. `messageSource.getMessage("msgs.forbidden", null, Locale.ENGLISH)` - в чем смысл такой локализации? может удалим совсем? или подсказать, как довести до рабочего состояния? вы уверены, что фронтенд к этому готов?
14. `@Bean` аннотация может быть на методе в классе - спринговой конфигурации, а не в другом бине (то есть не в Service, а например в Application), а в сервисе уже браться из спрингового контекста (аргументом конструктора)
15. UserDAO тоже сделайте спринговым бином (например, аннотацией `@Repository`)
16. Переделайте работу с ошибками - `return false` - это плохая обработка любых ошибок с базой. Логирование где есть, без стектрейса - это тоже не пойдёт.
17. Комментарии в коде зачем? У вас часто кода после комментариев меньше, чем самих комментариев - лучше переименуйте методы, чтобы они были понятнее (может они и так понятны?), а комментарии удалите такие
18. Тесты сделайте транзакционными, чтобы они не влияли никак друг на друга, и оставляли после себя чистую базу (только может с созданной через flyway схемой)

2017-10-19 08:40 UTC, isopov requested changes
Замечания в комментарии (иях)

2017-10-25 13:16 UTC, isopov commented
ping

2017-10-25 13:26 UTC, HaseProgram commented
У нас человек ошибся и создал отдельный пулреквест, вместо внесения сюда новых правок

2017-10-26 16:42 UTC, isopov commented
Ну а ответы какие-то я получу на вопросы? Например про такую организацию тестов - в других пакетах, чем основные исходники с категориями, интеграциионными тестами через failsafe-плагин - зачем это всё?

2017-10-28 16:49 UTC, KSolovyev commented
отдельный пул реквест не надо. Коммиты автоматически попадают в пул реквест, когда вы коммитите их в ветку

2017-10-31 09:43 UTC, isopov commented
Кажется, опять не в ту ветку были коммиты - вы мне лично говорили, что удалили нестандартные конфиги для тество, а они всё еще тут.

2017-11-01 08:17 UTC, isopov commented
Нифига себе - `@CrossOrigin(origins = "${frontend_url}")` - такое работает?

В общем круто - много вы тестов наколбасили. 

Про set_score - я из консоли разработчика в браузере  или курлом не смогу себе начитить счёт?

2017-11-01 13:26 UTC, HustonMmmavr commented
Да, с таким заданием константы адреса фронта в application,properties работает (нашел такое решение на stackoverflow).
Насчет set_score решение было принято в ночь перед предзащитой, пока единственное к чему мы пришли, это перенести всю логику игры на сервер.

2017-11-08 07:21 UTC, isopov approved these changes

2017-11-08 07:21 UTC, merged