РК3
java-park-mail-ru/LastUnion-09-2017 pull request #9
Opened 2017-12-20 11:33 UTC by strelnikoff

2017-12-20 11:58 UTC, KSolovyev commented
конфликты надо порешать

2017-12-20 12:30 UTC, strelnikoff commented
Выдайте права пожалуйста

2017-12-20 12:49 UTC, strelnikoff commented
конфликты решены

2017-12-20 22:32 UTC, KSolovyev commented
можно в описание пул реквеста ссылку на фронт?

2017-12-20 22:35 UTC, strelnikoff commented
lastunion.ml наш сайт, но фронт в данным момент еще не готов к многопользовательской игре

2017-12-20 23:11 UTC, KSolovyev requested changes
Механики нет, тестов нет. Смотреть дальше смысла нет

2017-12-20 23:11 UTC, KSolovyev commented on src/main/java/lastunion/application/game/websocket/GameSocketHandler.java
> +        /*final CommandMessage commandMessage;
закомментированного кода быть не должно

2017-12-20 23:11 UTC, KSolovyev commented on lastunion_server.iml
> +    <orderEntry type="library" name="Maven: org.jetbrains:annotations:15.0" level="project" />
этого файлы в репозитории быть не должно

2017-12-20 23:11 UTC, KSolovyev commented on src/main/java/lastunion/application/controllers/SignUpController.java
> +
мусорные изменения

2017-12-20 23:11 UTC, KSolovyev commented on src/main/java/lastunion/application/controllers/UserController.java
> +                                                 @RequestParam(value = "order", required = false) String order_
Зачем такая сложная валидация(((
можно же сюда было написать Integer и всё...

2017-12-20 23:11 UTC, KSolovyev commented on src/main/java/lastunion/application/game/messages/BaseMessage.java
> +        this.objectMapper = objectMapper;
не надо в модели хранить ObjectMapper

2017-12-20 23:11 UTC, KSolovyev commented on pom.xml
> +			<groupId>org.springframework.boot</groupId>
spring boot уже есть 1.5.9

2017-12-20 23:11 UTC, KSolovyev commented on src/main/java/lastunion/application/controllers/GamepadController.java
> +                messageSource.getMessage("12345", null, locale), null),
Если все хорошо, вы отвечаете 12345? В чем смысл?

2017-12-20 23:11 UTC, KSolovyev commented on src/main/java/lastunion/application/controllers/UserController.java
> +                                                 @RequestParam(value = "order", required = false) String order_
этот метод нужно переписать

2017-12-20 23:11 UTC, KSolovyev commented on src/main/java/lastunion/application/game/controllers/GameController.java
> +public class GameController {
Надо назвать GameService. В наших терминах это не контроллер

2017-12-20 23:11 UTC, KSolovyev commented on src/main/java/lastunion/application/game/controllers/GameController.java
> +    public GameView getView() {
надо удалить

2017-12-20 23:11 UTC, KSolovyev commented on pom.xml
> +		</dependency>
checkstyle plugin'а нет. Его использование обязательно

2017-12-20 23:11 UTC, KSolovyev commented on src/main/java/lastunion/application/game/services/GameService.java
> +            Vector<UserGameView> usersList = game.getGameView().getList();
Vector не надо использовать, мы говорили про это

2017-12-20 23:11 UTC, KSolovyev commented on src/main/java/lastunion/application/game/services/GameService.java
> +    private static final Map <String, Integer> userGameControllerId = new ConcurrentHashMap<>();
статические поля не надо использовать. Про это тоже говорили

2017-12-20 23:11 UTC, KSolovyev commented on src/main/java/lastunion/application/game/models/GameUserModel.java
> +        this.userView = userView;
omg! и ради этого мы столько сюда добирались. Это функция-прокрастинатор. Не делает ничего

2017-12-20 23:11 UTC, KSolovyev commented on src/main/java/lastunion/application/game/controllers/GameController.java
> +            if(user.getUserId()!=userId) {
Вам же IDE подсказывает, что так делать не надо. И правда, так делать не надо

2017-12-21 11:59 UTC, strelnikoff commented on pom.xml
> +		</dependency>
он там есть, просто был не настроен в ide и при запуске через нее не работал, при mvn package все ок
стиль кода поправил 
PS импортится со строки 115

2017-12-21 12:01 UTC, strelnikoff commented
Добавили игровую мехнаннику:
Два юзера заходят, подключаются и могут пересылать друг другу свои позиции
Сервер раздает им игровое поле

2017-12-22 21:33 UTC, KSolovyev commented
лучше поздно чем никогда

2017-12-22 21:33 UTC, KSolovyev approved these changes

2017-12-22 21:34 UTC, merged